### ISSUE TITLE
PA Review: User Authentication 

### ISSUE THREAD

**Issue by Noejoaquin** [Noejoaquin/EventLite#39]

**Comment by mfeniseycopes** [comment]
### Bug-free nav
- None found so far!

### Styling
- [x] If using labels, remove the placeholders on inputs
- [x] Inputs should be in a column not a row
- [x] Submit and Demo User buttons should also be in a column
- [x] Select a font closer to eventbrite's
- [x] Error display should match eventbrite's

### Seeds
- Yay for demo user!
